In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("college_student_placement_dataset.csv")

In [3]:
df.head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No

In [4]:
df.describe()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,99.471800,7.535673,7.532379,5.546400,4.970900,5.561800,2.513400
std,15.053101,1.447519,1.470141,2.873477,3.160103,2.900866,1.715959
min,41.000000,5.000000,4.540000,1.000000,0.000000,1.000000,0.000000
25%,89.000000,6.290000,6.290000,3.000000,2.000000,3.000000,1.000000
50%,99.000000,7.560000,7.550000,6.000000,5.000000,6.000000,3.000000
75%,110.000000,8.790000,8.770000,8.000000,8.000000,8.000000,4.000000
max,158.000000,10.000000,10.460000,10.000000,10.000000,10.000000,5.000000

In [5]:
df.isnull().sum()

College_ID                0
IQ                        0
Prev_Sem_Result           0
CGPA                      0
Academic_Performance      0
Internship_Experience     0
Extra_Curricular_Score    0
Communication_Skills      0
Projects_Completed        0
Placement                 0
dtype: int64

In [6]:
df.shape

(10000, 10)

In [7]:
df.head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No

In [4]:
df = df.drop(['College_ID'], axis=1)
df.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,107,6.61,6.28,8,No,8,8,4,No
1,97,5.52,5.37,8,No,7,8,0,No
2,109,5.36,5.83,9,No,3,1,1,No
3,122,5.47,5.75,6,Yes,1,6,1,No
4,96,7.91,7.69,7,No,8,10,2,No

In [5]:
df = pd.get_dummies(df, columns=['Internship_Experience', 'Placement'], drop_first=True)

In [10]:
df

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Internship_Experience_Yes,Placement_Yes
0,107,6.61,6.28,8,8,8,4,False,False
1,97,5.52,5.37,8,7,8,0,False,False
2,109,5.36,5.83,9,3,1,1,False,False
3,122,5.47,5.75,6,1,6,1,True,False
4,96,7.91,7.69,7,8,10,2,False,False
...,...,...,...,...,...,...,...,...,...
9995,119,8.41,8.29,4,1,8,0,False,True
9996,70,9.25,9.34,7,0,7,2,False,False
9997,89,6.08,6.25,3,3,9,5,True,False
9998,107,8.77,8.92,3,7,5,1,False,False
9999,109,9.41,9.77,8,3,5,5,False,False

In [11]:
df.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Internship_Experience_Yes,Placement_Yes
0,107,6.61,6.28,8,8,8,4,False,False
1,97,5.52,5.37,8,7,8,0,False,False
2,109,5.36,5.83,9,3,1,1,False,False
3,122,5.47,5.75,6,1,6,1,True,False
4,96,7.91,7.69,7,8,10,2,False,False

In [6]:
x = df.drop('Placement_Yes', axis=1)
y = df['Placement_Yes']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [10]:
# Check class imbalance before balancing
print("Before Balancing:")
print(f"Training set - Class distribution:\n{pd.Series(y_train).value_counts()}\n")
print(f"Percentage distribution:\n{pd.Series(y_train).value_counts(normalize=True) * 100}\n")

Before Balancing:
Training set - Class distribution:
Placement_Yes
False    6667
True     1333
Name: count, dtype: int64

Percentage distribution:
Placement_Yes
False    83.3375
True     16.6625
Name: proportion, dtype: float64

In [11]:
# OPTION 1: SMOTE (Synthetic Minority Over-sampling Technique)
# Generates synthetic samples for minority class
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
x_train_smote, y_train_smote = smote.fit_resample(x_train, y_train)

print("\n=== OPTION 1: SMOTE ===")
print(f"After SMOTE balancing:\n{pd.Series(y_train_smote).value_counts()}\n")
print(f"New training set size: {len(x_train_smote)}")
print(f"Percentage distribution:\n{pd.Series(y_train_smote).value_counts(normalize=True) * 100}")

=== OPTION 1: SMOTE ===
After SMOTE balancing:
Placement_Yes
False    6667
True     6667
Name: count, dtype: int64

New training set size: 13334
Percentage distribution:
Placement_Yes
False    50.0
True     50.0
Name: proportion, dtype: float64

In [12]:
# OPTION 2: Random Over-sampling
# Randomly duplicates minority class samples
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
x_train_ros, y_train_ros = ros.fit_resample(x_train, y_train)

print("\n=== OPTION 2: Random Over-sampling ===")
print(f"After Random Over-sampling:\n{pd.Series(y_train_ros).value_counts()}\n")
print(f"New training set size: {len(x_train_ros)}")
print(f"Percentage distribution:\n{pd.Series(y_train_ros).value_counts(normalize=True) * 100}")

=== OPTION 2: Random Over-sampling ===
After Random Over-sampling:
Placement_Yes
False    6667
True     6667
Name: count, dtype: int64

New training set size: 13334
Percentage distribution:
Placement_Yes
False    50.0
True     50.0
Name: proportion, dtype: float64

In [13]:
# OPTION 3: Random Under-sampling
# Randomly removes majority class samples
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=42)
x_train_rus, y_train_rus = rus.fit_resample(x_train, y_train)

print("\n=== OPTION 3: Random Under-sampling ===")
print(f"After Random Under-sampling:\n{pd.Series(y_train_rus).value_counts()}\n")
print(f"New training set size: {len(x_train_rus)}")
print(f"Percentage distribution:\n{pd.Series(y_train_rus).value_counts(normalize=True) * 100}")

=== OPTION 3: Random Under-sampling ===
After Random Under-sampling:
Placement_Yes
False    1333
True     1333
Name: count, dtype: int64

New training set size: 2666
Percentage distribution:
Placement_Yes
False    50.0
True     50.0
Name: proportion, dtype: float64

In [14]:
# OPTION 4: SMOTE + Undersampling (Hybrid - Recommended)
# Combines synthetic generation with removal of majority class
from imblearn.pipeline import Pipeline
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE

smote_und = Pipeline([
    ('smote', SMOTE(random_state=42)),
    ('undersampler', RandomUnderSampler(random_state=42))
])
x_train_hybrid, y_train_hybrid = smote_und.fit_resample(x_train, y_train)

print("\n=== OPTION 4: SMOTE + Under-sampling (Hybrid) ===")
print(f"After Hybrid balancing:\n{pd.Series(y_train_hybrid).value_counts()}\n")
print(f"New training set size: {len(x_train_hybrid)}")
print(f"Percentage distribution:\n{pd.Series(y_train_hybrid).value_counts(normalize=True) * 100}")

=== OPTION 4: SMOTE + Under-sampling (Hybrid) ===
After Hybrid balancing:
Placement_Yes
False    6667
True     6667
Name: count, dtype: int64

New training set size: 13334
Percentage distribution:
Placement_Yes
False    50.0
True     50.0
Name: proportion, dtype: float64

In [17]:
# COMPARISON: Train models with each balancing technique and evaluate
from sklearn.metrics import precision_recall_fscore_support, roc_auc_score, confusion_matrix

print("\n" + "="*80)
print("MODEL COMPARISON WITH DIFFERENT BALANCING TECHNIQUES")
print("="*80 + "\n")

balancing_options = {
    "No Balancing": (x_train, y_train),
    "SMOTE": (x_train_smote, y_train_smote),
    "Random Over-sampling": (x_train_ros, y_train_ros),
    "Random Under-sampling": (x_train_rus, y_train_rus),
    "SMOTE + Under-sampling": (x_train_hybrid, y_train_hybrid)
}

results = {}

for technique, (X_train, y_train_bal) in balancing_options.items():
    print(f"\n{'='*40}")
    print(f"Technique: {technique}")
    print(f"{'='*40}")
    print(f"Training set size: {len(X_train)}")

    # Train Random Forest (works well with balanced data)
    model = RandomForestClassifier(random_state=42, n_estimators=100)
    model.fit(X_train, y_train_bal)

    # Predictions on test set
    y_pred = model.predict(x_test)
    y_pred_proba = model.predict_proba(x_test)[:, 1]

    # Calculate metrics
    accuracy = model.score(x_test, y_test)
    precision, recall, f1, _ = precision_recall_fscore_support(y_test, y_pred, average='weighted')
    roc_auc = roc_auc_score(y_test, y_pred_proba)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

    # Store results
    results[technique] = {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'roc_auc': roc_auc,
        'tp': tp,
        'tn': tn,
        'fp': fp,
        'fn': fn
    }

    print(f"Accuracy:  {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-Score:  {f1:.4f}")
    print(f"ROC-AUC:   {roc_auc:.4f}")
    print(f"\nConfusion Matrix:")
    print(f"  True Negatives:  {tn}")
    print(f"  False Positives: {fp}")
    print(f"  False Negatives: {fn}")
    print(f"  True Positives:  {tp}")

# Summary comparison
print(f"\n\n{'='*80}")
print("SUMMARY COMPARISON")
print(f"{'='*80}\n")

comparison_df = pd.DataFrame(results).T
print(comparison_df[['accuracy', 'precision', 'recall', 'f1', 'roc_auc']].round(4))

print("\n✅ RECOMMENDATION: Choose the technique with best F1-Score (balances precision & recall)")
print("   For imbalanced data, F1-Score is often more important than Accuracy!")

================================================================================
MODEL COMPARISON WITH DIFFERENT BALANCING TECHNIQUES
================================================================================


========================================
Technique: No Balancing
========================================
Training set size: 8000
Accuracy:  1.0000
Precision: 1.0000
Recall:    1.0000
F1-Score:  1.0000
ROC-AUC:   1.0000

Confusion Matrix:
  True Negatives:  1674
  False Positives: 0
  False Negatives: 0
  True Positives:  326

========================================
Technique: SMOTE
========================================
Training set size: 13334
Accuracy:  0.9995
Precision: 0.9995
Recall:    0.9995
F1-Score:  0.9995
ROC-AUC:   1.0000

Confusion Matrix:
  True Negatives:  1673
  False Positives: 1
  False Negatives: 0
  True Positives:  326

========================================
Technique: Random Over-sampling
========================================
Training set size: 13334
Accuracy:  1.0000
Precision: 1.0000
Recall:    1.0000
F1-Score:  1.0000
ROC-AUC:   1.0000

Confusion Matrix:
  True Negatives:  1674
  False Positives: 0
  False Negatives: 0
  True Positives:  326

========================================
Technique: Random Under-sampling
========================================
Training set size: 2666
Accuracy:  1.0000
Precision: 1.0000
Recall:    1.0000
F1-Score:  1.0000
ROC-AUC:   1.0000

Confusion Matrix:
  True Negatives:  1674
  False Positives: 0
  False Negatives: 0
  True Positives:  326

========================================
Technique: SMOTE + Under-sampling
========================================
Training set size: 13334
Accuracy:  1.0000
Precision: 1.0000
Recall:    1.0000
F1-Score:  1.0000
ROC-AUC:   1.0000

Confusion Matrix:
  True Negatives:  1674
  False Positives: 0
  False Negatives: 0
  True Positives:  326


================================================================================
SUMMARY COMPARISON
================================================================================

                        accuracy  precision  recall      f1  roc_auc
No Balancing              1.0000     1.0000  1.0000  1.0000      1.0
SMOTE                     0.9995     0.9995  0.9995  0.9995      1.0
Random Over-sampling      1.0000     1.0000  1.0000  1.0000      1.0
Random Under-sampling     1.0000     1.0000  1.0000  1.0000      1.0
SMOTE + Under-sampling    1.0000     1.0000  1.0000  1.0000      1.0

✅ RECOMMENDATION: Choose the technique with best F1-Score (balances precision & recall)
   For imbalanced data, F1-Score is often more important than Accuracy!

In [18]:
# OPTION 5: Using Class Weights (No resampling needed)\n# Adjusts model weights to penalize misclassification of minority class\nfrom sklearn.utils.class_weight import compute_class_weight\n\nclass_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)\nclass_weight_dict = {0: class_weights[0], 1: class_weights[1]}\n\nprint(\"\\n=== OPTION 5: Class Weights (No Resampling) ===\")\nprint(f\"Class Weights: {class_weight_dict}\")\nprint(f\"Class 0 (No Internship) weight: {class_weights[0]:.4f}\")\nprint(f\"Class 1 (Yes Internship) weight: {class_weights[1]:.4f}\")\n\n# Train with class weights\nrf_weighted = RandomForestClassifier(random_state=42, n_estimators=100, class_weight='balanced')\nrf_weighted.fit(x_train, y_train)\n\ny_pred_weighted = rf_weighted.predict(x_test)\ny_pred_proba_weighted = rf_weighted.predict_proba(x_test)[:, 1]\n\naccuracy_weighted = rf_weighted.score(x_test, y_test)\nprecision_w, recall_w, f1_w, _ = precision_recall_fscore_support(y_test, y_pred_weighted, average='weighted')\nroc_auc_weighted = roc_auc_score(y_test, y_pred_proba_weighted)\n\nprint(f\"\\nResults with Class Weights:\")\nprint(f\"Accuracy:  {accuracy_weighted:.4f}\")\nprint(f\"Precision: {precision_w:.4f}\")\nprint(f\"Recall:    {recall_w:.4f}\")\nprint(f\"F1-Score:  {f1_w:.4f}\")\nprint(f\"ROC-AUC:   {roc_auc_weighted:.4f}\")"

In [19]:
# Visualize class distribution before and after balancing\nimport matplotlib.pyplot as plt\n\nfig, axes = plt.subplots(2, 3, figsize=(15, 8))\nfig.suptitle('Class Distribution: Original vs Balanced Datasets', fontsize=14, fontweight='bold')\n\n# Original (unbalanced)\naxes[0, 0].bar(['No', 'Yes'], [pd.Series(y_train).value_counts()[0], pd.Series(y_train).value_counts()[1]], color=['#ff6b6b', '#51cf66'])\naxes[0, 0].set_title('Original Data (Imbalanced)')\naxes[0, 0].set_ylabel('Count')\naxes[0, 0].set_ylim(0, max(pd.Series(y_train).value_counts()) * 1.1)\n\n# SMOTE\naxes[0, 1].bar(['No', 'Yes'], [pd.Series(y_train_smote).value_counts()[0], pd.Series(y_train_smote).value_counts()[1]], color=['#ff6b6b', '#51cf66'])\naxes[0, 1].set_title('SMOTE')\naxes[0, 1].set_ylabel('Count')\naxes[0, 1].set_ylim(0, max(pd.Series(y_train_smote).value_counts()) * 1.1)\n\n# Random Over-sampling\naxes[0, 2].bar(['No', 'Yes'], [pd.Series(y_train_ros).value_counts()[0], pd.Series(y_train_ros).value_counts()[1]], color=['#ff6b6b', '#51cf66'])\naxes[0, 2].set_title('Random Over-sampling')\naxes[0, 2].set_ylabel('Count')\naxes[0, 2].set_ylim(0, max(pd.Series(y_train_ros).value_counts()) * 1.1)\n\n# Random Under-sampling\naxes[1, 0].bar(['No', 'Yes'], [pd.Series(y_train_rus).value_counts()[0], pd.Series(y_train_rus).value_counts()[1]], color=['#ff6b6b', '#51cf66'])\naxes[1, 0].set_title('Random Under-sampling')\naxes[1, 0].set_ylabel('Count')\naxes[1, 0].set_ylim(0, max(pd.Series(y_train_rus).value_counts()) * 1.1)\n\n# SMOTE + Under-sampling\naxes[1, 1].bar(['No', 'Yes'], [pd.Series(y_train_hybrid).value_counts()[0], pd.Series(y_train_hybrid).value_counts()[1]], color=['#ff6b6b', '#51cf66'])\naxes[1, 1].set_title('SMOTE + Under-sampling (Hybrid)')\naxes[1, 1].set_ylabel('Count')\naxes[1, 1].set_ylim(0, max(pd.Series(y_train_hybrid).value_counts()) * 1.1)\n\n# F1-Scores comparison\ntechniques = list(results.keys())\nf1_scores = [results[tech]['f1'] for tech in techniques]\ncolors_bar = ['#ffd43b', '#a8e6cf', '#ffd3b6', '#ffaaa5', '#ff8b94']\naxes[1, 2].bar(range(len(techniques)), f1_scores, color=colors_bar)\naxes[1, 2].set_xticks(range(len(techniques)))\naxes[1, 2].set_xticklabels([t.replace(' ', '\\n') for t in techniques], fontsize=9)\naxes[1, 2].set_title('F1-Score Comparison')\naxes[1, 2].set_ylabel('F1-Score')\naxes[1, 2].set_ylim(0, 1)\naxes[1, 2].axhline(y=max(f1_scores), color='r', linestyle='--', alpha=0.3, label='Best')\n\nplt.tight_layout()\nplt.show()\n\nprint(\"\\n✅ Visualizations show class balance improvements and model performance!\")"

In [21]:
print("""
=== BALANCING TECHNIQUES GUIDE ===

1. SMOTE (Synthetic Minority Over-sampling Technique)
   - Generates synthetic samples using k-nearest neighbors
   - Best for: Small to medium datasets
   - Pros: Creates realistic synthetic samples
   - Cons: Can be slow with very large datasets

2. Random Over-sampling
   - Randomly duplicates minority class samples
   - Best for: Quick implementation
   - Pros: Simple, fast
   - Cons: Can cause overfitting due to duplicates

3. Random Under-sampling
   - Randomly removes majority class samples
   - Best for: Large datasets with lots of redundancy
   - Pros: Reduces dataset size, faster training
   - Cons: Loss of information from removed samples

4. SMOTE + Under-sampling (Hybrid) [RECOMMENDED]
   - Combines synthetic generation with selective removal
   - Best for: Most scenarios (balanced approach)
   - Pros: Preserves information while balancing
   - Cons: More parameters to tune

5. Class Weights
   - Adjusts model weights to penalize minority class errors
   - Best for: When you want to keep original data
   - Pros: No resampling, simpler approach
   - Cons: Less effective for severe imbalance

RECOMMENDATION:
Based on F1-Score comparison, choose the technique that scored highest!
F1-Score is ideal for imbalanced data as it balances precision & recall.
""")

=== BALANCING TECHNIQUES GUIDE ===

1. SMOTE (Synthetic Minority Over-sampling Technique)
   - Generates synthetic samples using k-nearest neighbors
   - Best for: Small to medium datasets
   - Pros: Creates realistic synthetic samples
   - Cons: Can be slow with very large datasets

2. Random Over-sampling
   - Randomly duplicates minority class samples
   - Best for: Quick implementation
   - Pros: Simple, fast
   - Cons: Can cause overfitting due to duplicates

3. Random Under-sampling
   - Randomly removes majority class samples
   - Best for: Large datasets with lots of redundancy
   - Pros: Reduces dataset size, faster training
   - Cons: Loss of information from removed samples

4. SMOTE + Under-sampling (Hybrid) [RECOMMENDED]
   - Combines synthetic generation with selective removal
   - Best for: Most scenarios (balanced approach)
   - Pros: Preserves information while balancing
   - Cons: More parameters to tune

5. Class Weights
   - Adjusts model weights to penalize minority class errors
   - Best for: When you want to keep original data
   - Pros: No resampling, simpler approach
   - Cons: Less effective for severe imbalance

RECOMMENDATION:
Based on F1-Score comparison, choose the technique that scored highest!
F1-Score is ideal for imbalanced data as it balances precision & recall.

In [22]:
# Print summary table
print("\n" + "="*90)
print("BALANCING RESULTS SUMMARY")
print("="*90)
summary_metrics = comparison_df[['accuracy', 'precision', 'recall', 'f1', 'roc_auc']].round(4)
print(summary_metrics.to_string())

best_technique = summary_metrics['f1'].idxmax()
best_f1_score = summary_metrics['f1'].max()

print("\n" + "="*90)
print(f"WINNER: {best_technique}")
print(f"F1-Score: {best_f1_score:.4f}")
print("="*90)
print("\nNext Step: Use the best balancing technique to train your final model!")
print(f"To use this technique, replace (x_train, y_train) with the balanced data.")
if "SMOTE" in best_technique and "Under" in best_technique:
    print("Use: x_train_hybrid, y_train_hybrid")
elif "SMOTE" in best_technique:
    print("Use: x_train_smote, y_train_smote")
elif "Over" in best_technique:
    print("Use: x_train_ros, y_train_ros")
elif "Under" in best_technique:
    print("Use: x_train_rus, y_train_rus")

==========================================================================================
BALANCING RESULTS SUMMARY
==========================================================================================
                        accuracy  precision  recall      f1  roc_auc
No Balancing              1.0000     1.0000  1.0000  1.0000      1.0
SMOTE                     0.9995     0.9995  0.9995  0.9995      1.0
Random Over-sampling      1.0000     1.0000  1.0000  1.0000      1.0
Random Under-sampling     1.0000     1.0000  1.0000  1.0000      1.0
SMOTE + Under-sampling    1.0000     1.0000  1.0000  1.0000      1.0

==========================================================================================
WINNER: No Balancing
F1-Score: 1.0000
==========================================================================================

Next Step: Use the best balancing technique to train your final model!
To use this technique, replace (x_train, y_train) with the balanced data.

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [16]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42)
}

In [17]:
for name, model in models.items():
    model.fit(x_train, y_train)
    score = model.score(x_test, y_test)  # This gives R² score
    print(f"{name}: Score = {score:.4f}")

Logistic Regression: Score = 0.9040
Decision Tree: Score = 1.0000
Random Forest: Score = 1.0000

In [19]:
# IQ , Prev_Sem_Result , CGPA ,Academic_Performance ,Internship_Experience ,Extra_Curricular_Score  ,Communication_Skills ,Projects_Completed
model.predict(np.array([[89, 8.6, 8.7, 0, 5.9, 8.0, 8, 3]]))  # Example input for prediction

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([ True])

In [20]:
model.predict(np.array([[50, 6.6, 6.7, 0, 5.9, 6.0, 5, 2]]))

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([False])

In [21]:
import pickle

In [22]:
with open("college_student_placement.pkl", "wb") as f:
    pickle.dump(model, f)

In [23]:
import json

In [24]:
columns = {
    'data_columns' : [col.lower() for col in x.columns]
}
with open("columns.json", "w") as f:
    f.write(json.dumps(columns))

In [25]:
# IQ , Prev_Sem_Result , CGPA ,Academic_Performance ,Internship_Experience ,Extra_Curricular_Score  ,Communication_Skills ,Projects_Completed
model.predict(np.array([[89, 8.6, 8.7, 0, 5.9, 8.0, 8, 3]]))  # Example input for prediction

c:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([ True])